import type { AppProps } from 'next/app';
import { IntlProvider } from 'react-intl';
import Head from 'next/head';
import '../styles/global.css';
import { Layout } from '../components/Layout';
import { ThemeProvider } from '../contexts/ThemeContext';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider>
      <IntlProvider locale="en">
        <Head>
          <title>Bodyweight Fun</title>
          {/* <meta name="description" content="Generated by create next app" /> */}
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* <link rel="stylesheet" href="//basehold.it/27"></link> */}
          <link
            rel="apple-touch-icon"
            sizes="180x180"
            href="/apple-touch-icon.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="32x32"
            href="/favicon-32x32.png"
          />
          <link
            rel="icon"
            type="image/png"
            sizes="16x16"
            href="/favicon-16x16.png"
          />
          <link rel="manifest" href="/site.webmanifest"></link>
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </IntlProvider>
    </ThemeProvider>
  );
}

export default MyApp;
